name: values
topic:
args:
  required:
  - name: obj
    type: [object]
    desc:
  optional: []
returns:
  type: array
  desc:
desc: |
  Returns the values of the provided object.
  Note that because JSON hashes are inheritently unordered, the
  values associated with the provided object `obj` are inheritently
  unordered.  Implementations are not required to return values in
  any specific order.  For example, given the input:
  
  ```
  {"a": "first", "b": "second", "c": "third"}
  ```
  
  The expression `values(@)` could have any of these return values:
  
  
  * `["first", "second", "third"]`
  
  
  * `["first", "third", "second"]`
  
  
  * `["second", "first", "third"]`
  
  
  * `["second", "third", "first"]`
  
  
  * `["third", "first", "second"]`
  
  
  * `["third", "second", "first"]`
  
  If you would like a specific order, consider using the
  `sort` or `sort_by` functions.
examples:
- context: {"foo": "baz", "bar": "bam"}
  args: ["@"]
  returns: ["baz", "bam"]
- context: ["a", "b"]
  args: ["@"]
  returns: "<error: invalid-type>"
- context: false
  args: ["@"]
  returns: "<error: invalid-type>"
