name: Validate tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          cache: pip
          cache-dependency-path: bin/requirements.txt
      - name: Validate tests
        run: "ls grammar/*.json functions/*.json | xargs -I {} jsonschema test_schema.json -i {}"