name: Trigger website update
on:
  push:
    tags: 
      - v*
      - 2015-09-05-9e8d0e3
    branches:
      - main
jobs:
  dispatch:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'jmespath-community',
            repo: 'jmespath.site',
            workflow_id: 'build.yaml',
            ref: 'main',
            inputs: { version: '${{ github.ref_name }}' }
          })
